### PR TITLE
added a .gitignore for node-models,package.json for server and server.js

### PR DESCRIPTION
**Pull request by freebattie**
added a .gitignore file for node-models, added package.json for the server side and a server.js,

### CODE REVIEW

**Comment by JaxomofRuatha** [comment]
Looks good as the very basic Express server, fine by me to merge. May want to update file structure once React front end and more back end components are added in.

**Review by jchritton — COMMENTED** [review]
Looks good as the very basic Express server, fine by me to merge. May want to update file structure once React front end and more back end components are added in.

**Review by YourMCGeek — APPROVED** [review]
Will have to update folder structure, along with the .gitignore. 

:+1:

**Comment by YourMCGeek** [comment]
[Added a .gitignore for node-models,package.json for server and server.js](https://trello.com/c/FerJVYqj/26-added-a-gitignore-for-node-modelspackagejson-for-server-and-serverjs)

**Pull request merged**
